VERSION_NAME=3.6.1
android.useAndroidX=true
org.gradle.jvmargs=-Xmx4g
kotlin.daemon.jvmargs=-Xmx4g

# gradle-maven-publish configuration
SONATYPE_HOST=CENTRAL_PORTAL
RELEASE_SIGNING_ENABLED=true
GROUP=com.github.ajalt.colormath
POM_DESCRIPTION=Multiplatform color space conversions for Kotlin
POM_INCEPTION_YEAR=2021
POM_URL=https://github.com/ajalt/colormath/
POM_LICENSE_NAME=The MIT License
POM_LICENSE_URL=https://opensource.org/licenses/MIT
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/ajalt/colormath/
POM_SCM_CONNECTION=scm:git:git://github.com/ajalt/colormath.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/ajalt/colormath.git
POM_DEVELOPER_ID=ajalt
POM_DEVELOPER_NAME=AJ Alt
POM_DEVELOPER_URL=https://github.com/ajalt/
