[versions]
kotlin = "2.4.10"
compose = "1.11.1"
kotest = "6.2.4"

[libraries]

# used in extensions
androidx-annotation =  "androidx.annotation:annotation:1.10.0"
compose-ui-graphics = { module = "org.jetbrains.compose.ui:ui-graphics", version.ref = "compose" }

# used in tests
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-tables = { module = "io.kotest:kotest-assertions-table", version.ref = "kotest" }
junit =  "junit:junit:4.13.2"
robolectric =  "org.robolectric:robolectric:4.16.1"


[plugins]
dokka = "org.jetbrains.dokka:2.2.0"
publish = "com.vanniktech.maven.publish:0.37.0"
kotlinBinaryCompatibilityValidator = "org.jetbrains.kotlinx.binary-compatibility-validator:0.18.1"

# used in extensions
android-kmp-library = "com.android.kotlin.multiplatform.library:9.3.1"

# used in samples
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
