name: Build

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'samples/**'
      - '*.md'
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - 'samples/**'
      - '*.md'
jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: ubuntu-latest
            GRADLE_ARGS: |
              apiCheck
              :test:check
              :colormath:compileKotlinLinuxArm64
              :colormath:compileKotlinWasmJs
              :extensions:colormath-ext-jetpack-compose:check
              :extensions:colormath-ext-android-colorint:check
              :extensions:colormath-ext-android-color:check
              --stacktrace
          - os: macos-latest
            GRADLE_ARGS: |
              macosX64Test
              :colormath:compileKotlinMacosArm64
              iosX64Test
              tvosX64Test
              iosSimulatorArm64Test
              tvosSimulatorArm64Test
              watchosSimulatorArm64Test
              --stacktrace
          - os: windows-latest
            GRADLE_ARGS: mingwX64Test --stacktrace
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew ${{matrix.GRADLE_ARGS}}
      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: build-report-${{ matrix.os }}
          path: '**/build/reports'
  publish:
    needs: test
    runs-on: macos-latest
    if: ${{ github.ref == 'refs/heads/master' && github.repository == 'ajalt/colormath' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
      - name: Deploy to sonatype
        # disable configuration cache due to https://github.com/gradle/gradle/issues/22779
        run: ./gradlew publishToMavenCentral -PsnapshotVersion=true --no-configuration-cache
    env:
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralPassword }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKey }}
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralUsername }}
env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.project.kotlin.incremental.multiplatform=false -Dorg.gradle.project.kotlin.native.disableCompilerDaemon=true -Dorg.gradle.jvmargs="-Dfile.encoding=UTF-8"
